[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint]
load-plugins = ["pylint_django","pylint_pytest"]
django-settings-module = "pulp_science.settings"

[tool.pylint.format]
max-line-length = 120

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "pulp_science.settings"
