# Generated by Django 4.2.6 on 2023-10-11 01:58

import django.db.models.deletion
from django.db import migrations, models


def add_default_categories(apps, schema_editor):
    # We can't import the Category model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("homepage", "Category")
    Category(name="physics").save()
    Category(name="biology").save()
    Category(name="chemistry").save()
    Category(name="informatics").save()
    Category(name="mathematics").save()


def remove_default_categories(apps, schema_editor):
    # We can't import the Category model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Category = apps.get_model("homepage", "Category")
    Category.objects.get(name="physics").delete()
    Category.objects.get(name="biology").delete()
    Category.objects.get(name="chemistry").delete()
    Category.objects.get(name="informatics").delete()
    Category.objects.get(name="mathematics").delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commentable",
            fields=[
                ("commentable_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Followable",
            fields=[
                ("followable_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Versionable",
            fields=[
                ("versionable_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version_group", models.BigIntegerField()),
                ("version_number", models.PositiveIntegerField()),
                ("created", models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "versionable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.versionable",
                    ),
                ),
                (
                    "commentable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.commentable",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("subtitle", models.CharField(max_length=128, null=True)),
                ("content", models.TextField()),
                ("thumbnail", models.ImageField(null=True, upload_to="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("moderator", "moderator"),
                            ("private", "private"),
                            ("review", "review"),
                            ("follower", "follower"),
                            ("user", "user"),
                            ("public", "public"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
            ],
            bases=("homepage.commentable", "homepage.versionable"),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "versionable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.versionable",
                    ),
                ),
                (
                    "commentable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.commentable",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
            ],
            bases=("homepage.commentable", "homepage.versionable"),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "followable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.followable",
                    ),
                ),
                (
                    "commentable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.commentable",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("subtitle", models.CharField(max_length=128, null=True)),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(null=True, upload_to="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("moderator", "moderator"),
                            ("private", "private"),
                            ("review", "review"),
                            ("follower", "follower"),
                            ("user", "user"),
                            ("public", "public"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
            ],
            bases=("homepage.commentable", "homepage.followable"),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "commentable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.commentable",
                    ),
                ),
                (
                    "followable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="homepage.followable",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=32)),
            ],
            bases=("homepage.followable", "homepage.commentable"),
        ),
        migrations.AddConstraint(
            model_name="versionable",
            constraint=models.UniqueConstraint(fields=("version_group", "version_number"), name="unique_version"),
        ),
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(blank=True, related_name="followed_by", to="homepage.followable"),
        ),
        migrations.AddField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_by", to="homepage.commentable"),
        ),
        migrations.AddField(
            model_name="project",
            name="related_authors",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.user"),
        ),
        migrations.AddField(
            model_name="project",
            name="related_categories",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.category"),
        ),
        migrations.AddField(
            model_name="project",
            name="related_tags",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.tag"),
        ),
        migrations.AddField(
            model_name="comment",
            name="commented_on",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="comments", to="homepage.commentable"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="written_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="written_comments",
                to="homepage.user",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_authors",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.user"),
        ),
        migrations.AddField(
            model_name="article",
            name="related_categories",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.category"),
        ),
        migrations.AddField(
            model_name="article",
            name="related_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_articles",
                to="homepage.project",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="related_tags",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.tag"),
        ),
        migrations.RunPython(add_default_categories, reverse_code=remove_default_categories),
    ]
