# Generated by Django 4.2.6 on 2023-10-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="related_authors",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.user"),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_categories",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.category"),
        ),
        migrations.AlterField(
            model_name="article",
            name="related_tags",
            field=models.ManyToManyField(blank=True, related_name="related_articles", to="homepage.tag"),
        ),
        migrations.AlterField(
            model_name="project",
            name="related_authors",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.user"),
        ),
        migrations.AlterField(
            model_name="project",
            name="related_categories",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.category"),
        ),
        migrations.AlterField(
            model_name="project",
            name="related_tags",
            field=models.ManyToManyField(blank=True, related_name="related_projects", to="homepage.tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(blank=True, related_name="followed_by", to="homepage.followable"),
        ),
        migrations.AlterField(
            model_name="user",
            name="likes",
            field=models.ManyToManyField(blank=True, related_name="liked_by", to="homepage.commentable"),
        ),
    ]
