# Generated by Django 4.2.6 on 2023-10-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0002_alter_article_related_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="commentable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="homepage.commentable",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="commentable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="homepage.commentable",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="commentable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="homepage.commentable",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followable_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                to="homepage.followable",
            ),
        ),
    ]
