name: "Django Unittests on test and production environment"

on: [push]
jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
        tox: [tests, tests_prod]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
#      - name: Create .env file
#        run: python create_env_file.py
      - name: Start containers
        run: docker-compose up -d
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Test with tox and django
        run: |
          tox -e ${{ matrix.tox }}
